function adjective() {
	return random([
		"in-house",
		"empowering",
		"end-to-end",
		"disruptive",
		"innovative",
		"strategic",
		"guerilla",
		"hyper-personalized",
		"enterprise",
		"contextually aware",
		"ninja grade",
		"omni-channel",
	    "holistic",
	    "pragmatic",
	    "hedonistic",
	    "lean",
        "ninja",
	    "dynamically generated",
	    "static-positioned",
	    "situational aware",
	    "self-descriptive",
	    "tangential",
	    "greenfield",
	    "passive",
	    "active",
        "artisanal",
        "bleeding edge",
        "consumer-facing",
        "data-driven",
        "freemium",
        "game-changer",
        "impactful",
        "mission critical",
        "non-trivial",
        "no-brainer",
        "orthogonal",
        "push-pull",
        "quick and dirty",
        "t-shaped",
        "vanilla",
        "viral"
	]);
}
