function technique() {
	return random([
		"competitor analysis",
		"user survey",
		"Atomic Design",
		"interview",
		"contextual enquiry",
		"focus group",
		"brainstorming",
		"ideation session",
		"affinity diagramming",
		"task analysis",
		"paper prototyping",
		"heuristic evaluation",
		"storyboarding",
		"performance testing",
		"subjective evaluation",
		"critical incidence technique",
		"remote evaluation",
		"personas",
   		"gamification",
		"user journey",
		"longitudinal study",
		"ethnography research",
		"cultural probe",
		"participant observation",
		"eyetracking",
		"keystroke level modelling",
		"hypotesys deconstruction",
		"charrette",
		"sketch-to-code",
		"research wall",
		"concept model",
		"service blueprint",
		"mental model",
		"evangelicalism session",
		"healthcheck",
		"product in a box",
		"process mapping",
		"design system",
		"diary study",
		"Figma prototype",
		"Airtable document",
		"roadmap"
	]);
}
